cd C:\Users\HP\Interns_and_Projects\PBE\simulations\PAA\30_MD\uncharged
python inputgen_all.py
cd C:\Users\HP\Interns_and_Projects\PBE\simulations\PAA\35_MD\PAA35
python inputgen_all.py
cd C:\Users\HP\Interns_and_Projects\PBE\simulations\PAA\40_MD\PAH40
python inputgen_all.py
cd C:\Users\HP\Interns_and_Projects\PBE\simulations\PAA\45_MD\PAH45
python inputgen_all.py
cd C:\Users\HP\Interns_and_Projects\PBE\simulations\PAA\50_MD\PAA
python inputgen_all.py
